# Generated by Django 2.0.6 on 2018-07-16 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HinhThuc',
            fields=[
                ('ma_ht', models.IntegerField(primary_key=True, serialize=False)),
                ('ten_ht', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loai',
            fields=[
                ('ma_loai', models.IntegerField(primary_key=True, serialize=False)),
                ('ten_loai', models.CharField(max_length=45)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('cha', models.ForeignKey(blank=True, db_column='cha', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Loai')),
            ],
        ),
        migrations.CreateModel(
            name='LoaiSach',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ma_loai', models.ForeignKey(db_column='ma_loai', on_delete=django.db.models.deletion.DO_NOTHING, to='home.Loai')),
            ],
        ),
        migrations.CreateModel(
            name='NgonNgu',
            fields=[
                ('ma_nn', models.IntegerField(primary_key=True, serialize=False)),
                ('ten_nn', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NhanXet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField(null=True)),
                ('ngay_dang', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sach',
            fields=[
                ('ma_sach', models.IntegerField(primary_key=True, serialize=False)),
                ('ten_sach', models.CharField(max_length=150)),
                ('bia_sach', models.ImageField(null=True, upload_to='')),
                ('isbn', models.CharField(max_length=15)),
                ('so_trang', models.IntegerField(blank=True, null=True)),
                ('namxb', models.TextField(blank=True, null=True)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('hinh_thuc', models.ForeignKey(blank=True, db_column='hinh_thuc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.HinhThuc')),
                ('ngon_ngu', models.ForeignKey(blank=True, db_column='ngon_ngu', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.NgonNgu')),
            ],
        ),
        migrations.CreateModel(
            name='TacGia',
            fields=[
                ('ma_tg', models.IntegerField(primary_key=True, serialize=False)),
                ('ten_tg', models.CharField(max_length=100)),
                ('hinh', models.ImageField(null=True, upload_to='')),
                ('nam_sinh', models.TextField(blank=True, null=True)),
                ('que_quan', models.CharField(blank=True, max_length=150, null=True)),
                ('mo_ta', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TacGiaSach',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ma_sach', models.ForeignKey(db_column='ma_sach', on_delete=django.db.models.deletion.DO_NOTHING, to='home.Sach')),
                ('ma_tg', models.ForeignKey(db_column='ma_tg', on_delete=django.db.models.deletion.DO_NOTHING, to='home.TacGia')),
            ],
        ),
        migrations.CreateModel(
            name='TacGiaTheLoai',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ma_loai', models.ForeignKey(blank=True, db_column='ma_loai', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Loai')),
                ('ma_tg', models.ForeignKey(blank=True, db_column='ma_tg', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.TacGia')),
            ],
        ),
        migrations.AddField(
            model_name='nhanxet',
            name='sach',
            field=models.ForeignKey(db_column='sach', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nhan_xet', to='home.Sach'),
        ),
        migrations.AddField(
            model_name='nhanxet',
            name='tac_gia',
            field=models.ForeignKey(db_column='tac_gia', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loaisach',
            name='ma_sach',
            field=models.ForeignKey(db_column='ma_sach', on_delete=django.db.models.deletion.DO_NOTHING, to='home.Sach'),
        ),
    ]
