# Generated by Django 2.0.6 on 2018-07-17 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sach',
            name='phien_ban',
            field=models.ForeignKey(blank=True, db_column='phien_ban', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.PhienBan'),
        ),
    ]
