# Generated by Django 2.0.6 on 2018-07-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sach',
            name='namxb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tacgia',
            name='nam_sinh',
            field=models.IntegerField(default=0),
        ),
    ]
