# Generated by Django 2.0.6 on 2018-07-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180717_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hinhthuc',
            name='ma_ht',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loai',
            name='ma_loai',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ngonngu',
            name='ma_nn',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sach',
            name='ma_sach',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tacgia',
            name='ma_tg',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
