# Generated by Django 2.0.6 on 2018-07-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180717_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='tacgia',
            name='the_loai',
            field=models.ManyToManyField(to='home.Loai'),
        ),
    ]
